{{- if and .Values.externaldb.enabled .Values.externaldb.broker.serviceInstanceName }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ template "common.names.fullname" . }}-binding
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  instanceRef:
    name: {{ .Values.externaldb.broker.serviceInstanceName }}
  secretName: {{ template "node.secretName" . }}
{{- end }}
